package com.example.timer.presentation.service.config

const val TIMER_CHANNEL_ID: String = "TIMER_CHANNEL_ID"
const val TIMER_CHANNEL_NAME: String = "TIMER_CHANNEL_NAME"
const val ACTION_TOGGLE_RESUME_PAUSE = "ACTION_TOGGLE_RESUME_PAUSE"
const val ACTION_PHASE_PREVIOUS = "ACTION_PHASE_PREVIOUS"
const val ACTION_PHASE_NEXT = "ACTION_PHASE_NEXT"
const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
const val NOTIFICATION_ID: Int = 1
const val REQUEST_CODE_OPEN_ACTIVITY_ID: Int = 0
const val REQUEST_CODE_RESUME_PAUSE_SERVICE_ID: Int = 1
const val REQUEST_CODE_PHASE_PREVIOUS_SERVICE_ID: Int = 2
const val REQUEST_CODE_PHASE_NEXT_SERVICE_ID: Int = 3
const val SOUND_VOLUME = 100
const val DURATION_MS_SOUND = 250
const val EXTRA_SEQUENCE_ID = "EXTRA_SEQUENCE_ID"