@startuml
start

repeat
  :Главный экран (Список последовательностей);

  if (Действие пользователя?) then (Настройки)
    :Экран настроек;
    :Изменение параметров;
    :Сохранение изменений в DataStore;
  else if (Экран Редактирование / Создание)
    :Экран редактирования;
    :Настройка интервалов и цветов;
    :Сохранение изменений в SQLite;
  else (Экран таймера)
    :Запуск таймера;
    :Запуск TimerService (Foreground);
    partition "Работа сервиса" {
      :Отсчет фаз и циклов;
      :Обновление уведомления;
      :Обработка команд паузы/пропуска/остановки;
    }
  endif

  note right: Возврат к списку происходит\nавтоматически после завершения\nили сохранения действий

repeat while (Приложение активно)

stop
@endum